name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node_version: 12.x
      
    # Instalar as dependência NPM/Yarn
    - name: Install dependencies
      run: yarn
       
    # Executar a build
    - name: Run build
      run: yarn build
    
    # Copiar código para Digital Ocean
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app/gobarber-backend-ts"
      
    # Executar "yarn" na Digital Ocean
    - name: Install dependencies on Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/gobarber-backend-ts
          yarn
      
    # Executar as migrations do TypeORM
    - name: Run migrations on Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/gobarber-backend-ts
          ./node_mobules/.bin/typeorm migration:run
      
    # Restart no servidor Node.js
    - name: Restart Node.js Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: pm2 restart gobarber-api
